nelmio_api_doc:
    documentation:
        info:
            title: Web Atrio Test Api
            description: This is an awesome app!
            version: 1.0.0  
        paths:
            /personnes:
                get:
                    tags:
                    - Personne
                post:
                    tags:
                    - Personne
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        host_patterns:
            - ^/api\.